### ISSUE TITLE
[BUG] Emotes Cause Extreme Desync in Multiplayer

### ISSUE THREAD

**Issue by floofytail22** [DS-GAMING-SE/Sonic#32]
Using emotes or pulling up the wheel causes extreme player position desync between client and host in multiplayer. It seems to be related to latency, as it almost never happens when using local multiplayer mod testing, but is consistent in actual multiplayer. It is not just a visual issue, and feels and looks like very bad rubber-banding. This affects both the client and host, and only players emoting as Sonic. 

Video of issue: https://youtu.be/Kmk9lNy4HRk

Enabled mods:

- Sonic and its dependencies.
- Debug Toolkit and its dependencies.
- Badass Emotes and its dependencies.

**Comment by DS-GAMING-SE** [comment]
I was never gonna find a bug like this by myself. I _think_ I fixed it but it's hard for me to test, so let me know if it's been fixed or not

**Comment by floofytail22** [comment]
It seems to be slightly better. Desync isn't immediate, but still happens after maybe 10-30 seconds or so.
